
spring:
    datasource:
        url: jdbc:mysql://localhost/notflix_nexus?useSSL=false
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: update
    userdata:
        admin:
            username: admin
            password: admin
            authorities: ROLE_ADMIN, ROLE_USER