notflix:
    roles:
        admin: "ROLE_ADMIN"
        user: "ROLE_USER"
    users:
        - username: admin
          password: admin
          authorities: ${notflix.roles.admin}, ${notflix.roles.user}

    fail:
        message: "not found"

spring:
    mvc:
        format:
            date: yyyy-MM-dd
    datasource:
        url: jdbc:mysql://nfnexus.c94wpx4yhkpj.eu-north-1.rds.amazonaws.com:3306/nfnexus?useSSL=false
        username: nnadmin
        password: '!nnadmin23'
    jpa:
        hibernate:
            ddl-auto: update

server:
    port: 8080


api:
    url: https://api.themoviedb.org
    key: 7c0af285bec5ba381f87bb2a0eea17a0
    searchbyname: /3/search/movie?query=
    getbyid: /3/movie/
    discover: /3/discover/movie
    keywords: /3/movie/{movie_id}/keywords
    recommendations: /3/movie/{movie_id}/recommendations