notflix:
    roles:
        admin: "ROLE_ADMIN"
        user: "ROLE_USER"
    users:
        - username: admin
          password: admin
          authorities: ${notflix.roles.admin}, ${notflix.roles.user}
        - username: dummy
          password: dummy
          authorities: ${notflix.roles.user}
    movies:
        - imdbId: "1234"
          title: "movie"
          genres:
            - "love"
            - "romance"
          releaseYear: 2022
        - imdbId: "5678"
          title: "film"
          genres:
            - "action"
            - "thriller"
          releaseYear: 1970
    fail:
        message: Movie not found.

spring:
    mvc:
        format:
            date: yyyy-MM-dd
    datasource:
        url: jdbc:mysql://localhost/notflix_nexus?useSSL=false
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: update

api:
    url: https://api.themoviedb.org
    key: 7c0af285bec5ba381f87bb2a0eea17a0
    searchbyname: /3/search/movie?query=
    getbyid: /3/movie/