authentication:
    roles:
        admin: "ROLE_ADMIN"
        user: "ROLE_USER"
    users:
        - username: admin
          password: admin
          authorities: ${authentication.roles.admin}, ${authentication.roles.user}
        - username: dummy
          password: dummy
          authorities: ${authentication.roles.user}

movies:
    default:
        - title: movie
          genre: love
          releaseYear: 2022
        - title: film
          genre: action
          releaseYear: 1970

spring:
    datasource:
        url: jdbc:mysql://localhost/notflix_nexus?useSSL=false
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: update